### ISSUE TITLE
RB-T: META: Hydrate devportal-tutorials-rb repository 

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-rb#1]
As Advocates, we need a place to put our active ruby tutorials and present them in a nice way for users. We also need an initial set of tutorials described in story/issue format on the repository

**AC**
- [x] Follow the general file structure of https://github.com/steemit/devportal-tutorials-js
- [x] Include the tutorial_structure.md from devportal-tutorials-js
- [x] Include contributing guidelines
